FileViewer/Controllers/FileController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using FileViewer.Models;
using System.Net.Http;

namespace FileViewer.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            IEnumerable<MVCFileModel> fileList;
            HttpResponseMessage response = GlobalUtilities.WebApiClient.GetAsync("files").Result;
            fileList = response.Content.ReadAsAsync<IEnumerable<MVCFileModel>>().Result;
            return View(fileList);
        }

        public ActionResult AddOrEdit(int id = 0) {
            if (id == 0)
            {
                return View(new MVCFileModel());
            }
            else
            {
                HttpResponseMessage res = GlobalUtilities.WebApiClient.GetAsync("Files/"+id.ToString()).Result;
                return View(res.Content.ReadAsAsync<MVCFileModel>().Result);
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(MVCFileModel file) {
            if (file.id == 0)
            {
                HttpResponseMessage res = GlobalUtilities.WebApiClient.PostAsJsonAsync("Files", file).Result;
                TempData["SuccessMsg"] = "Saved";
            }
            else {
                HttpResponseMessage res = GlobalUtilities.WebApiClient.PutAsJsonAsync("Files/" + file.id.ToString(),file).Result;
                TempData["SuccessMsg"] = "Updated";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id) {
            //Deletefile
            HttpResponseMessage res = GlobalUtilities.WebApiClient.DeleteAsync("Files/" + id.ToString()).Result;
            TempData["SuccessMsg"] = "Deleted";
            return RedirectToAction("Index");
        }

    }
}

FileViewer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/alertifyjs/alertify.min.css" rel="=stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("File Viewer", "Index", "File", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>